more fine-grained process control

diff --git a/run-one b/run-one
--- a/run-one
+++ b/run-one
@@ -2,28 +2,31 @@
 # SPDX-License-Identifier: GPL-3.0-or-later
 # Copyright (C) 2026 Yuri Cherio
 
-unset debug_file_path # Path to the debug file
-unset lock_wait # max time to wait for the lock to become available
-unset kill_wait # run-this-one: send SIGKILL to the lock holder after this secs
-unset lock_token # Use this token instead of calculating user command hash
-unset flock_err_exit_code # Custom flock error exit code
-unset terminate_others # This flag is set when either called as run-this-one or '-x' is specified
+unset wait_lock # wait for the lock to become available before quitting or killing others
+unset wait_term # run-this-one: keep sending SIGTERM for this long
+unset wait_kill # run-this-one: keep sending SIGKILL for this long
 unset run_anyway # run another instance after lock timeout no matter what
+unset lock_token # command identifier token; defaults to command hash
+unset lock_check # just test if another process holds the lock
+unset fail_exit_code # custom error exit code
+unset debug_file_path # Path to the debug file
 
 while [ $# -gt 0 ] ; do
 	case "$1" in
-	-E) { shift; flock_err_exit_code="$1"; shift; } ;; # Custom flock error exist code
-	-D) { shift; debug_file_path="$1"; shift; } ;; #
-	-w) { shift; lock_wait="$1"; shift; } ;; # wait for the lock to become available
-	-a) { run_anyway="$1"; shift; } ;;
-	-k) { shift; kill_wait="$1"; shift; } ;; # kill the other process instances after this secs
-	-T) { shift; lock_token="$1"; shift; } ;; #
-	-x) { terminate_others="$1"; shift; } ;; # force the priviledged run-this-one
+	-w) { shift; wait_lock="$1"; } ;; # wait for the lock to become available
+	-t) { shift; wait_term="$1"; } ;; # TERM the other process instances after this secs
+	-k) { shift; wait_kill="$1"; } ;; # KILL the other process instances after this secs
+	-a) run_anyway="$1" ;;
+	-i) { shift; lock_token="$1"; } ;; # command identifier token; defaults to command hash
+	-T) lock_check="$1" ;; #
+	-E) { shift; fail_exit_code="$1"; } ;; # Custom error exit code
+	-D) { shift; debug_file_path="$1"; } ;; #
 	-h|--help) exec man -P cat "${0##*/}" ;; # Display help
-	'') shift ;; # Ignore empty arguments
+	'') ;; # Ignore empty arguments
 	--) { shift; break; } ;; # The rest is the user supplied command line
 	*) { break; } ;; # Beginning of the user supplied command line
 	esac
+	shift
 done
 
 _debug() {
@@ -33,16 +36,17 @@ _debug() {
 
 [ $# -eq 0 ] && _debug "ERROR: no arguments specified" 1
 
-: "${flock_err_exit_code:=122}" # When undefined, set the default
+: "${fail_exit_code:=122}" # When undefined, set the default
 
-[ "${0##*/}" = "run-this-one" ] && terminate_others="-x"
+[ "${wait_lock##*[!0-9]}" = "$wait_lock" ] || _debug "Error: option -w requires an integer" 1
+[ "${wait_term##*[!0-9]}" = "$wait_term" ] || _debug "Error: option -k requires an integer" 1
+[ "${wait_kill##*[!0-9]}" = "$wait_kill" ] || _debug "Error: option -K requires an integer" 1
+[ "${fail_exit_code##*[!0-9]}" = "$fail_exit_code" ] || _debug "Error: option -E requires an integer" 1
 
-[ -z "$terminate_others" ] && [ -n "$kill_wait" ] &&
-	_debug "Error: option -k is a noop without -x"
-
-[ "${lock_wait##*[!0-9]}" = "$lock_wait" ] || _debug "Error: option -w requires an integer" 1
-[ "${kill_wait##*[!0-9]}" = "$kill_wait" ] || _debug "Error: option -k requires an integer" 1
-[ "${flock_err_exit_code##*[!0-9]}" = "$flock_err_exit_code" ] || _debug "Error: option -E requires an integer" 1
+if [ "${0##*/}" = "run-this-one" ]; then
+	# by default wait for 10 minutes while terminating other processes
+	[ "${wait_term:-0}" -eq '0' ] && [ "${wait_kill:-0}" -eq '0' ] && wait_term="600"
+fi
 
 unset lock_file_dir # Lock file directory
 unset uid # System user ID
@@ -71,119 +75,116 @@ if [ -d "$xdg_runtime_dir" ] || mkdir -m 700 "$xdg_runtime_dir" 2>/dev/null; the
 	lock_file_dir="$xdg_runtime_dir"
 else
 	# Make an attempt to create a hash directory in /dev/shm
-	try_global_dir "/dev/shm/${prog_name}_${uid:=$(id -u)}" ||
+	try_global_dir "/dev/shm/${prog_name}-${uid:=$(id -u)}" ||
 		# Try creating it in /tmp; let's hope it's mounted as tmpfs
-		try_global_dir "/tmp/${prog_name}_${uid}" ||
+		try_global_dir "/tmp/${prog_name}-${uid}" ||
 		# Sadly, this system doesn't see to be suitable - QUIT
-		_debug "Failed to setup lock file" "$flock_err_exit_code"
+		_debug "Failed to setup lock file" "$fail_exit_code"
 fi
 
 [ -n "$lock_file_dir" ] ||
-	_debug "Failed to identify lock file directory" "$flock_err_exit_code"
+	_debug "Failed to identify lock file directory" "$fail_exit_code"
 
 # If custom command id token is not provided use command signature
 lock_file_base="$(printf "%s" "${lock_token:-$*}" | sha256sum)}" # Hash the id token
 lock_file_path="$lock_file_dir/${lock_file_base%% *}" # Ignore whitespace and what follows
 _debug "Lock file: $lock_file_path"
+
 _debug "[$$] Command: ${0##*/} $*"
 
-unset flock_exit_code
+find_lock_holders() {
+	# Scanning /proc is orders of magnitude faster than using lsof or fuser
+	find /proc -maxdepth 1 -name '[1-9]*' -uid "${uid:=$(id -u)}" -printf '%p/fd/9\n' 2>/dev/null |
+		xargs stat -c '%N' 2>/dev/null |
+		grep -oP "(?<=/proc/)\d+(?=/fd/\\d+\\Q' -> '$lock_file_path'\\E)" # | paste -sd " " -
+}
+
+if [ -n "$lock_check" ]; then
+	lock_holder_pids="$(find_lock_holders)"
+	[ -n "$lock_holder_pids" ] && echo $lock_holder_pids
+	exec [ -z "$lock_holder_pids" ] # success when no one is holding the lock
+fi
+
 # Waits for the semaphore to acquire the lock and run user command
-exec_with_flock() { # This function only returns if lock was unsuccessful
-	_flock_wait="$1"; shift # Wait time to acquire the lock, can be 0
-	flock_exit_code="$flock_err_exit_code" # exit code in case redirection fails
+flock_and_exec() { # This function only returns if lock was unsuccessful
+	_fwait_lock="$1"; shift # Wait time to acquire the lock, can be 0
 	{ # Acquire the lock and run the user command
-		flock -x -w "$_flock_wait" -E "$flock_err_exit_code" 9 # Acquire the lock
-		flock_exit_code=$? # This is either 0 or $flock_err_exit_code
-		if [ "$flock_exit_code" -eq 0 ]; then # We successfully acquired the lock
+		if flock -x -w "$_fwait_lock" -E "$fail_exit_code" 9; then # We successfully acquired the lock
 			_debug "Lock acquired, running command: $*"
 			exec "$@" # Execute the user command
 		fi
 	} 9>"$lock_file_path"
 }
 
-# The action is determined from either the symbolic link to the utility or from -x parameter
-if [ -z "$terminate_others" ]; then
-	# Lock the semaphore and run the command
-	exec_with_flock "${lock_wait:-0}" "$@"
-	if [ -n "$run_anyway" ]; then
-		_debug "Could not aquire the lock but running anyway"
-		rm -f "$lock_file_path"; # remove the lock file
-		exec_with_flock 0 "$@"
-	fi
-	# We are here it means flock failed. That's okay, it happens
-	_debug "Another process is already running" "$flock_exit_code"
-else
-	# Stop other process instances and execute this one
-	[ -n "$lock_wait" ] && quit_after="$(date -d "+$lock_wait sec" +%s)"
-	[ -n "$kill_wait" ] && kill_after="$(date -d "+$kill_wait sec" +%s)"
-	# _debug "quit_after: $quit_after, kill_after: $kill_after"
+flock_and_exec 0 "$@" # just try it
 
-	kill_signal="TERM"
-	pause_secs=0
-	# Deadline for when when no one holds the lock but we can't acquire it
-	unset issue1_limit
+if [ "${wait_lock:-0}" -gt 0 ]; then
+	ts_end="$(date -d "+$wait_lock sec" +%s)"
+	wait_left_secs="$wait_lock"
+	while [ "$wait_left_secs" -gt 0 ]; do
+		flock_and_exec "$wait_left_secs" "$@" # this does not return if lock is successful
+		wait_left_secs="$((ts_end - $(date +%s)))"
+	done
+fi
 
+send_signal() {
+	sig="$1"; shift
+
+	lock_holder_pids="$(find_lock_holders)"
+	[ -z "$lock_holder_pids" ] && return 1
+
+	_debug "Sending signal $sig to $lock_holder_pids"
+	kill -s "$sig" $lock_holder_pids # return success if at least one terminated
+}
+
+unset ts_issue1_quit # quit when no one holds the lock, but it can't be acquired
+
+signal_lock_and_run() {
+	duration="$1"; shift
+	sig="$1"; shift
+
+	ts_end="$(date -d "+$duration sec" +%s)"
+	pause_secs="0"
 	while :; do
-		# This call does not return if the lock is acquired successfully
-		exec_with_flock "$pause_secs" "$@"
+		flock_and_exec "$pause_secs" "$@" # this does not return if lock is successful
 
-		[ "$pause_secs" -lt 20 ] && pause_secs="$((pause_secs + 1))"
-		time_now="$(date +%s)"
+		ts_now="$(date +%s)"
+		wait_left_secs="$((ts_end - ts_now))"
+		[ "$wait_left_secs" -le 0 ] && break
+		pause_secs="$((pause_secs + 1))"
+		[ "$pause_secs" -gt 15 ] && pause_secs="15"
+		[ "$pause_secs" -gt "$wait_left_secs" ] && pause_secs="$wait_left_secs"
 
-		# If a wait timeout was specified, check if we've exceeded it
-		if [ -n "$lock_wait" ]; then
-			if [ "$quit_after" -le "$time_now" ]; then # wait timeout exceeded
-				if [ -n "$run_anyway" ]; then
-					rm -f "$lock_file_path"; # remove the lock file
-					exec_with_flock 0 "$@"
-					_debug "Another process is running" "$flock_exit_code"
-				fi
-				# We waited too long for the lock to be acquired
-				_debug "Could not obtain the lock in time" "$flock_exit_code"
-			elif [ "$quit_after" -lt "$((time_now + pause_secs))" ]; then
-				# No need to pause for longer than the timeout limit
-				pause_secs="$((quit_after - time_now))"
-			fi
-		fi
 
-		# Check if SIGKILL needs to be sent
-		if [ -n "$kill_wait" ]; then
-			if [ "$kill_after" -le "$time_now" ]; then # Time to kill other process instances
-				kill_signal="KILL" # Switch to sending SIGKILL this point on
-				pause_secs=1 # Reset signal frequency interval
-				_debug "Time to send SIGKILL"
-				unset kill_wait # This check is no longer needed - disable
-			elif [ "$kill_after" -lt "$((time_now + pause_secs))" ]; then
-				# No need to pause for longer than the timeout limit
-				pause_secs="$((kill_after - time_now))"
-			fi
-		fi
-
-		: "${uid:=$(id -u)}" # cache the uid for faster access
-		# Identify the other processes that hold the lock
-		pids_to_kill="$( # Scanning /proc is orders of magnitude faster than using lsof or fuser
-			find /proc -maxdepth 1 -name '[1-9]*' -uid "$uid" -printf '%p/fd/9\n' 2>/dev/null |
-				xargs stat -c '%N' 2>/dev/null |
-				grep -F "' -> '$lock_file_path'" |
-				grep -oP "(?<=/proc/)\d+" # | paste -sd " " -
-		)"
-
-		# Terminate other process instances (if any) that hold the lock
-		if [ -n "$pids_to_kill" ]; then
-			_debug "Sending signal $kill_signal to $pids_to_kill"
-			kill -s "$kill_signal" $pids_to_kill
-			unset issue1_limit
-		else
-			# Suspisious state: no other process seems to be holding the lock but the lock could not be acquired
-			if [ -z "$issue1_limit" ]; then # Set the time limit
-				issue1_limit="$(date -d "+300 sec" +%s)" # bail in 5 min
+		if send_signal "$sig" ; then
+			unset ts_issue1_quit
+		else # there are not any processes holding the lock
+			if [ -z "$ts_issue1_quit" ]; then
+				ts_issue1_quit="$(date -d "+300 sec" +%s)" # bail in 5 min
+				pause_secs=1 # reduce pause to 1 second
 				_debug "Abnormality: no other process seems to be holding the lock and yet the lock could not be acquired" # ¯\_(ツ)_/¯
-			elif [ "$issue1_limit" -le "$time_now" ]; then
-				# Something's fishy. Bailing to prevent an infinite loop
+			elif [ "$ts_issue1_quit" -gt "$(date +%s)" ]; then
 				_debug "Abnormality persists, giving up" 1
 			fi
 		fi
-
 	done
+
+	_debug "Expired $duration sec for signal $sig"
+}
+
+if [ "${wait_term:-0}" -gt 0 ]; then
+	signal_lock_and_run "$wait_term" "TERM" "$@"
 fi
+
+if [ "${wait_kill:-0}" -gt 0 ]; then
+	signal_lock_and_run "$wait_kill" "KILL" "$@"
+fi
+
+if [ -n "$run_anyway" ]; then
+	_debug "Running anyway, replacing the lock file"
+	rm -f "$lock_file_path"; # remove the lock file
+	flock_and_exec 0 "$@"
+	_debug "Still can not acquire the lock" "$fail_exit_code"
+fi
+
+exit "$fail_exit_code"
